apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: helabooking
type: Opaque
data:
  # postgres:postgres (base64 encoded)
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXM=
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: helabooking
type: Opaque
data:
  # guest:guest (base64 encoded)
  username: Z3Vlc3Q=
  password: Z3Vlc3Q=
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: helabooking
type: Opaque
data:
  # JWT secret key (base64 encoded)
  secret: UTJoaGJtZGxWR2hwYzFObFkzSmxkRmRwZEdoRmVHRnRjR3hsUm05eVNHVnNZVUp2YjJ0cGJtZEZibU55ZVhCMGFXOXVMVEV5TXpRMU5qYzRPVEF4TWpNME5UWTNPRGt3
